receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
exporters:
  debug:
    verbosity: detailed
  otlp/jaeger:
    endpoint: "jaeger-container:4317"  # Replace with your Jaeger endpoint
    tls:
      insecure: true   # Optional, if Jaeger doesn't use TLS
  logging:
    verbosity: detailed
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, otlp/jaeger]
    logs:
      receivers: [ otlp ]
      exporters: [ otlp/jaeger ]
#    metrics:
#      receivers: [otlp]
#      exporters: [debug, otlp/jaeger]
#    logs:
#      receivers: [otlp]
#      exporters: [debug, otlp/jaeger]
