receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
exporters:
  debug:
    verbosity: detailed
  otlp/jaeger:
    endpoint: "jaeger-container:4317"
    tls:
      insecure: true
  logging:
    verbosity: detailed
service:
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ debug, otlp/jaeger ]
    logs:
      receivers: [ otlp ]
      exporters: [ debug ]
    metrics:
      receivers: [ otlp ]
      exporters: [ debug ]
