receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
exporters:
  debug:
    verbosity: detailed
  otlp/jaeger:
    endpoint: "jaeger-container:4317"
    tls:
      insecure: true
  otlp/metrics:
    endpoint: "data-prepper:4901"
    tls:
      insecure: true
  otlp/traces:
    endpoint: "data-prepper:4909"
    tls:
      insecure: true
  otlp/logs:
    endpoint: "data-prepper:4902"
    tls:
      insecure: true
service:
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ otlp/jaeger, otlp/traces ]
    logs:
      receivers: [ otlp ]
      exporters: [ otlp/logs ]
    metrics:
      receivers: [ otlp ]
      exporters: [ otlp/metrics ]

