services:
  collector:
    image: otel/opentelemetry-collector
    container_name: otlp-collector
    ports:
      - 4317:4317
      - 4318:4318
    volumes:
      - ./collector-config.yml:/etc/otelcol/config.yaml
    networks:
     - tracing-integration
  jaeger:
    image: jaegertracing/all-in-one:1.54.0
    container_name: jaeger-container
    ports:
      - 16686:16686
      - 14250:14250
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 14268:14268
      - 14269:14269
      - 9411:9411
    networks:
      - tracing-integration

networks:
  tracing-integration:

